version: "3"


services:
  app:
    image: alpine
    restart: unless-stopped
    expose:
      - 8080

  user-app:
    image: brawleryura/multimodule_test/user-app
    restart: unless-stopped
    ports:
      - "8080:8080"

  theme-app:
    image: brawleryura/multimodule_test/theme-app
    restart: unless-stopped
    ports:
      - "8082:8080"

  message-app:
    image: brawleryura/multimodule_test/message-app
    restart: unless-stopped
    ports:
      - "8083:8080"

  gateway-app:
    image: brawleryura/multimodule_test/gateway-app
    restart: unless-stopped
    ports:
      - "8079:8080"

  forum-app:
    image: brawleryura/multimodule_test/forum-app
    restart: unless-stopped
    ports:
      - "8084:8080"

  category-app:
    image: brawleryura/multimodule_test/category-app
    restart: unless-stopped
    ports:
      - "8081:8080"

  postgres:
    hostname: postgres
    image: postgres:14.1-alpine
    container_name: test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mm_test"
    ports:
      - "15432:5432"