app:
  security:
    jwt-token:
      permit-all:
        - /api/user/register
        - /api/user/login
        - /api/user/get
        - /api/category/getCategoriesStructure
        - /api/theme/getThemeListInCategory/
        - /api/theme/getThemeList
        - /api/message/getMessagesInTheme/
        - /api/forum/findBySubstring
        - /api/message/getMessages
      root-path: /api
      secret: qqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrtttyyyuuuiiiooopppqqqwwweeerrrttty
      expiration: 86400000
    integrations:
      root-path: /integration
      api-key: ac816388c1c44ac2b2ae431f89c82e7e345d25a0e6474e75a78f9a5ce496060c